# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Weekly developer digest

on:
  schedule:
  # Every Friday morning (UTC)
  - cron: '0 7 * * 5'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    # Mark this week's issues as stale and close them after one month.
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 7
        days-before-close: 31
        ignore-updates: true
        stale-issue-label: 'Archived'
        stale-pr-label: 'Archived'
        operations-per-run: 200
